server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          url:
          search-paths:
            springcloid config
      label: master

Eureka:
  client:
    service-url:
      defaulyZone: http://localhost:7001/eureka
